### ISSUE TITLE
can not find iphone devices which I plugged into my mac

### ISSUE THREAD

**Issue by krisdyZJU** [matthutchinson/videosnap#11]
actually I want to use this command line tool to capture video of my iphone which I plugged into my mac when I do some manipulations on it, but after I execute videosnap in my mac: ./video -l, it only list my facetime HD camera, but no my iphone, but I can see my iphone when I open quicktime, any suggestions,thanks.

<img width="214" alt="2016-05-20 11 27 28" src="https://cloud.githubusercontent.com/assets/9692934/15416440/1a9a2fba-1e7e-11e6-876c-c59589dfa279.png">

**Comment by matthutchinson** [comment]
So the reason for this is, I still haven't updated videosnap to use the AVFoundation framework.  The command is still using the old QTKit libraries.

I had started an [av-foundation](https://github.com/matthutchinson/videosnap/tree/av-foundation) branch a while ago, but many things have got in the way and I haven't had the time i'd like to devote to this. As soon as it's release I'll update this issue to notify you..

**Comment by brooksc** [comment]
+1 for this request -- found videosnap as I was looking for an alternative to the broken and abandoned xrecord project... https://github.com/WPO-Foundation/xrecord/issues . Please let us know if you add ios recording!  I often capture ios videos for bug reports and I'd love to automate this!

**Comment by matthutchinson** [comment]
Sorry I have had time to work on this project for a while, pull requests are always welcome!

**Comment by muuuh** [comment]
https://stackoverflow.com/a/32703158

It seem to work somehow with this patch:

`#import <CoreMediaIO/CMIOHardware.h>`

```
int main(int argc, const char * argv[]) {
    @autoreleasepool {
        CMIOObjectPropertyAddress prop = {
            kCMIOHardwarePropertyAllowScreenCaptureDevices,
            kCMIOObjectPropertyScopeGlobal,
            kCMIOObjectPropertyElementMaster
        };
        UInt32 allow = 1;
        CMIOObjectSetPropertyData(kCMIOObjectSystemObject, &prop, 0, NULL, sizeof(allow), &allow);
}
```

**Comment by matthutchinson** [comment]
Thanks @muuuh for this suggestion!

I've just [released v0.0.5](https://github.com/matthutchinson/videosnap/tree/master/release), you should now be able to capture from any attached iOS device!

Here's [an example capture](https://www.dropbox.com/s/094sb2mgp28pwj1/videosnap-example-ios-capture.mov?dl=1) from my iPhone X at `-p High` quality

**Comment by guptapunit** [comment]
Hi, the **videosnap -l** command does not list my connected iPhone i am using the latest version.

Attaching the logs below if it helps, do let me know if i am doing something wrong of if there are some permissions to be enabled/disabled either on the device or the mac.
```
Punits-MacBook-Pro:bin punitgupta$ videosnap -l
Found 1 available video devices:
* FaceTime HD Camera
```
```
(base) Punits-MacBook-Pro:videosnap-main punitgupta$ videosnap -h
VideoSnap (0.0.6)

Record video and audio from a capture device

You can specify which device to capture from, the duration, encoding and a delay
period (before capturing starts). You can also disable audio recording.
By default videosnap will capture both video and audio from the default capture
device at 30fps, with a Medium quality preset and a short (0.5s) warm-up delay.

If no duration is specified, videosnap will record until you cancel with [Ctrl+c]
You can also use videosnap to list attached capture devices by name.

  usage: videosnap [options] [file ...]
example: videosnap -t 5.75 -d 'Built-in iSight' -p 'High' my_movie.mov

  -l          List attached capture devices
  -w x.xx     Set delay before capturing starts (in seconds, default 0.5s)
  -t x.xx     Set duration of video (in seconds)
  -d device   Set the capture device (by name, use -l to list attached devices)
  --no-audio  Don't capture audio
  -v          Turn ON verbose mode (OFF by default)
  -h          Show help
  -p          Set the encoding preset (Medium by default)
                High
                Medium (default)
                Low
                640x480
                1280x720
```
**As you can see the version is 0.0.6. 
The Version of Mac OS i am trying this on is Big Sur 11.2.2.**

Something I've noticed is that if I launch Quicktime Player, select New Movie Recording and select my device as a Camera source, then my device is listed when i run the " videosnap -l " command.

**Comment by matthutchinson** [comment]
I've replicated the issue here, same problem; and if I close Quicktime Player, the device is no longer listed.
I've re-opened this issue for now.

When I have some time available I'll try to investigate further.

**Comment by vrbajiva** [comment]
Hi! 🙂   Sadly, I encountered this issue too.

Connected iOS devices are not listed using `videosnap -l` (while QuickTime is running), although I can see them listed in QuickTime video sources.

MacBook Air (M1, 2020)

**Comment by IntergalacticPenguin** [comment]
Hey @matthutchinson, I know you are probably quite busy lately as we all are, but this is a huge opportunity to fix a problem potentionaly affecting hundreds of M1 chip Mac users. 

You can really make a difference by enabling iOS device screen recording more efficient for many of the [Mobile Toolkit](https://github.com/IntergalacticPenguin/mobile-toolkit) users as well as all of those using your Videosnap tool on latest Macbooks. 

Please take a quick look at this issue, maybe there is a simple hotfix just waiting for your action.

Thank you for your time and all your priceless contributions to our community.

**Comment by matthutchinson** [comment]
I'll try to investigate this weekend, or early next week.

**Comment by matthutchinson** [comment]
Still having some intermittent issues with this.. looking into it further

**Comment by IntergalacticPenguin** [comment]
Hi @matthutchinson so there are still some issues on M1 after all. I am not able to capture any recording. See the verbose output below:
```
(caught signal: [2])
(stopping recording)
(finished writing to movie file)
(stopping capture session)

Failed to capture any video
(reason: Cannot Record)
```
Are there any steps we can take to fix this, or everything we can do is to hope that Apple will resolve this somehow?
Also i think that this issue should be reopened, since it is not resolved for now.

**Comment by matthutchinson** [comment]
So the issue title/description here is based around 

> can not find iphone devices which I plugged into my Mac

That should now be resolved on M1 and Intel Macs.  Capturing from a connected iPhone on an M1 Mac is currently broken, so we need another issue for that.  Capturing from a connected webcam *should* work tho.  

Can you pls create another issue and describe what's happening ... i.e. what command you're running and the output with -v flag on.

**Comment by IntergalacticPenguin** [comment]
Alright, im on it. 🤝
