### ISSUE TITLE
Resultant Files Won't Play on iOS 12 

### ISSUE THREAD

**Issue by allankenneth** [matthutchinson/videosnap#16]
I apologize if this has nothing to do with this program; I suspect this is the case, but I've searched about high and low and cannot figure it out. I'm wondering if you might have some time to offer any input/advice.

I'm running on a Mac Mini (Late 2014) 2.6ghz i5, running **the public beta of Mojave 10.14.3**. 

When I execute the program, I immediately get the following output:

`GVA encoder info: recomputed for fps: 29.970030, got size in pics: 29, got size in sec: 1.000000`

Everything appears to run smoothly after this, and it creates a file that I can view as I would expect... 

The thing is: the files won't play on iOS. I see a thumbnail, and when I tap it, the timeline appears to load, but then just nothing happens; no audio, no video.

I've been uploading the files to iCloud Drive and sharing them out to family members; they can only view the files on a Mac (haven't tried on a windows box). Out of 6-7 different iOS devices (mostly running iOS 12), nobody can view the videos (unless they use a Mac).

I've tried several other more direct file transfers to account for iCloud Drive weirdness (e.g. directly to my iPhone X); nothing plays.

The only thing that **does** work on iOS is to view things through VLC.

Are you aware of any codec changes that might have happened in AVFoundation in Mojave or its betas that might cause this? Any idea how to work around it? I'm going to attempt to un-enrol from the beta and see what happens.

Many thanks for your time and expertise! Feel free to close this without comment if you just don't have time.

**Comment by matthutchinson** [comment]
:D I don't have time right now, but leaving this one open and tagging as a bug

**Comment by matthutchinson** [comment]
I've tried this with iOS 13 and iOS 14 beta and not had any issues ... Can you try again with the latest v0.0.5 release against an iOS 12 device?
