### ISSUE TITLE
unknown duration?

### ISSUE THREAD

**Issue by elijahchancey** [matthutchinson/videosnap#6]
What if you want to record a video of an unknown length? Is there a way to have it record the video until you press Ctrl+C?

**Comment by cdcv** [comment]
How about the ability to STOP video recording from a command line command?  That'd be, well, great!

**Comment by matthutchinson** [comment]
I've just release v0.0.3 of VideoSnap, which now (by default) records video until you cancel with `Ctrl+c`.  This (to me) is a correct way to STOP video recording from the command line.

So either kill the `videosnap` process (with a [kill](http://www.manpages.info/macosx/kill.2.html) command) or simply press `Ctrl+c` at anytime to stop recording.  Even if you do specify a duration, pressing `Ctrl+c` before that time is up, will cancel the capture and write to the movie file.
