### ISSUE TITLE
Running multiple videosnap sessions simultaneously

### ISSUE THREAD

**Issue by miketissenbaum** [matthutchinson/videosnap#7]
I was wondering if it was possible to run multiple versions of videosnap (say I have 3 cameras attached) is there a way to launch videosnap on each one simultaneously (perhaps by defining which attached camera I am want for each)? Or will it kill the earlier session when I run the new one?

**Comment by matthutchinson** [comment]
After thinking this through, i'd rather not have this as a feature. I'd rather have the tool be closer to the [unix philosophy](http://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well) of doing one thing well. If I added this I feel it would bloat the command code.

For capturing from multiple cam's you can use multiple processes of this command to do it (as you've explained).

**Comment by miketissenbaum** [comment]
I agree - it ended up working perfectly by doing it in the command line and
I actually like the simplicity
