### ISSUE TITLE
Is there a way to record audio only with no video?

### ISSUE THREAD

**Issue by macosxservice** [matthutchinson/videosnap#8]
This code is a true gem! I've got it up and running, and it works as stated.  My one question: I see that it is possible to record video with no audio, but is it possible tor record audio only (no video)?  Any adjustments I could do from my end, or would this require a revision from ground up?  Any input or ideas are appreciated! Sorry if this is the improper way to ask, I'm unfamiliar. Thanks for sharing!

**Comment by matthutchinson** [comment]
Thanks for your feedback, this would certainly be possible, I'd have to decide on a default audio file format to output (and possibly let you specify this on the command line too).  Currently the command uses `QTCompressionOptionsHighQualityAACAudio` for audio compression.  

I've marked this as an enhancement and put it on my todo list.  Until I get around to it you could try something like [sox](http://brewformulas.org/Sox) for command line audio recording,  `brew install sox`

**Comment by matthutchinson** [comment]
After thinking this through, i'd rather not have this as a feature. 

I'd rather have the tool be closer to the [unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) of doing one thing well, and for VideoSnap, this will always be about recording Video.

If I added this I feel it would bloat the code having to deal with audio compression and other formatting options.

The `sox` command should do everything you'd need e.g.

    brew install sox
    sox -d my_recording.mp3 
    # and hit ctrl+c to stop recording
