### ISSUE TITLE
Add crop

### ISSUE THREAD

**Issue by Benxamin** [matthutchinson/videosnap#9]
I would like a CLI for recording a specific part of the screen with Quicktime Player
Current manual method:
**Quicktime Player (10.4)**
- File > New Screen Recording
- Click red circle "Record" button.
- Drag with mouse rectangle dimensions that you want to record. (Starts recording on mouseup).
- Stop recording by clicking round black circle in menu bar.

Need to be able to pass TopLeft(x,y) and BottomRight(x,y) to record just that part of the screen.

**Comment by matthutchinson** [comment]
Sorry, VideoSnap is primary used for capturing video from attached camera's (not screen recording).  You could try building an [Automater](http://en.wikipedia.org/wiki/Automator_(software)) script for the 4 step process you describe above.
